cloud:
  aws:
    credentials:
      access-key: AKIA2DZ3J5RZ2OOF2LYD
      secret-key: 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
    region:
      static: eu-west-3
    stack:
      auto: false

apllication:
  bucket:
    name: imagestorage323

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB